ns_param	.323		text/h323
ns_param	.3dm		x-world/x-3dmf
ns_param	.3dmf		x-world/x-3dmf
ns_param	.acx		application/internet-property-stream 
ns_param	.axs		application/olescript 
ns_param	.aab		application/x-authorware-bin
ns_param	.aam		application/x-authorware-map
ns_param	.aas		application/x-authorware-seg
ns_param	.abc		text/vnd.abc
ns_param	.acgi		text/html
ns_param	.afl		video/animaflex
ns_param	.ai		application/postscript
ns_param	.aif		audio/x-aiff
ns_param	.aifc		audio/x-aiff
ns_param	.aiff		audio/x-aiff
ns_param	.aim		application/x-aim
ns_param	.aip		text/x-audiosoft-intra
ns_param	.ani		application/x-navi-animation
ns_param	.aos		application/x-nokia-9000-communicator-add-on-software
ns_param	.aps		application/mime
ns_param	.arc		application/octet-stream
ns_param	.arj		application/arj
ns_param	.arj		application/octet-stream
ns_param	.art		image/x-jg
ns_param	.asf		video/x-ms-asf
ns_param	.asm		text/x-asm
ns_param	.asp		text/asp
ns_param	.asx		video/x-ms-asf
ns_param	.asr		video/x-ms-asf
ns_param	.au		audio/basic
ns_param	.avi		video/x-msvideo
ns_param	.avi		video/x-msvideo
ns_param	.avs		video/avs-video
ns_param	.bas		text/plain 
ns_param	.bin		application/octet-stream 
ns_param	.bcpio		application/x-bcpio
ns_param	.bm		image/bmp
ns_param	.bmp		image/bmp
ns_param	.boo		application/book
ns_param	.book		application/book
ns_param	.boz		application/x-bzip2
ns_param	.bsh		application/x-bsh
ns_param	.bz		application/x-bzip
ns_param	.bz2		application/x-bzip2
ns_param	.clp		application/x-msclip 
ns_param	.cmx		image/x-cmx 
ns_param	.cod		image/cis-cod 
ns_param	.crd		application/x-mscardfile 
ns_param	.c		text/plain
ns_param	.c++		text/plain
ns_param	.cat		application/vnd.ms-pki.seccat
ns_param	.cc		text/plain
ns_param	.ccad		application/clariscad
ns_param	.cco		application/x-cocoa
ns_param	.cdf		application/x-cdf
ns_param	.cer		application/x-x509-ca-cert
ns_param	.cha		application/x-chat
ns_param	.chat		application/x-chat
ns_param	.class		application/octet-stream
ns_param	.com		application/octet-stream
ns_param	.conf		text/plain
ns_param	.cpio		application/x-cpio
ns_param	.cpp		text/plain
ns_param	.cpt		application/x-cpt
ns_param	.crl		application/pkix-crl
ns_param	.crt		application/x-x509-ca-cert
ns_param	.csh		application/x-csh
ns_param	.css		text/css
ns_param	.cxx		text/plain
ns_param	.dll		application/x-msdownload 
ns_param	.dms		application/octet-stream 
ns_param	.dcr		application/x-director
ns_param	.deepv		application/x-deepv
ns_param	.def		text/plain
ns_param	.der		application/x-x509-ca-cert
ns_param	.dif		video/x-dv
ns_param	.dir		application/x-director
ns_param	.dl		video/x-dl
ns_param	.doc		application/msword
ns_param	.dot		application/msword
ns_param	.dp		application/commonground
ns_param	.drw		application/drafting
ns_param	.dump		application/octet-stream
ns_param	.dv		video/x-dv
ns_param	.dvi		application/x-dvi
ns_param	.dwf		model/vnd.dwf
ns_param	.dwg		image/vnd.dwg
ns_param	.dxf		application/dxf
ns_param	.dxr		application/x-director
ns_param	.el		text/x-script.elisp
ns_param	.elc		application/x-elc
ns_param	.env		application/x-envoy
ns_param	.eps		application/postscript
ns_param	.es		application/x-esrehber
ns_param	.etx		text/x-setext
ns_param	.evy		application/envoy
ns_param	.evy		application/x-envoy
ns_param	.exe		application/octet-stream
ns_param	.fif		application/fractals 
ns_param	.flr		x-world/x-vrml 
ns_param	.f		text/plain
ns_param	.f77		text/x-fortran
ns_param	.f90		text/plain
ns_param	.fdf		application/vnd.fdf
ns_param	.fli		video/x-fli
ns_param	.flo		image/florian
ns_param	.flx		text/vnd.fmi.flexstor
ns_param	.fmf		video/x-atomic3d-feature
ns_param	.for		text/plain
ns_param	.fpx		image/vnd.fpx
ns_param	.frl		application/freeloader
ns_param	.funk		audio/make
ns_param	.g		text/plain
ns_param	.g3		image/g3fax
ns_param	.gif		image/gif
ns_param	.gl		video/gl
ns_param	.gsd		audio/x-gsm
ns_param	.gsm		audio/x-gsm
ns_param	.gsp		application/x-gsp
ns_param	.gss		application/x-gss
ns_param	.gtar		application/x-gtar
ns_param	.gz		application/x-gzip
ns_param	.gzip		application/x-gzip
ns_param	.h		text/plain
ns_param	.hdf		application/x-hdf
ns_param	.help		application/x-helpfile
ns_param	.hgl		application/vnd.hp-HPGL
ns_param	.hh		text/plain
ns_param	.hlb		text/x-script
ns_param	.hlp		application/winhlp
ns_param	.hpg		application/vnd.hp-HPGL
ns_param	.hpgl		application/vnd.hp-HPGL
ns_param	.hqx		application/mac-binhex40
ns_param	.hta		application/hta
ns_param	.htc		text/x-component
ns_param	.htm		text/html
ns_param	.html		text/html
ns_param	.htmls		text/html
ns_param	.htt		text/webviewhtml
ns_param	.htx		text/html
ns_param	.iii		application/x-iphone 
ns_param	.isp		application/x-internet-signup 
ns_param	.ice		x-conference/x-cooltalk
ns_param	.ico		image/x-icon
ns_param	.idc		text/plain
ns_param	.ief		image/ief
ns_param	.iefs		image/ief
ns_param	.iges		application/iges
ns_param	.igs		application/iges
ns_param	.ima		application/x-ima
ns_param	.imap		application/x-httpd-imap
ns_param	.inf		application/inf
ns_param	.ins		application/x-internett-signup
ns_param	.ip		application/x-ip2
ns_param	.isu		video/x-isvideo
ns_param	.it		audio/it
ns_param	.iv		application/x-inventor
ns_param	.ivr		i-world/i-vrml
ns_param	.ivy		application/x-livescreen
ns_param	.jam		audio/x-jam
ns_param	.jav		text/plain
ns_param	.java		text/plain
ns_param	.jcm		application/x-java-commerce
ns_param	.jfif		image/jpeg
ns_param	.jfif-tbnl	image/jpeg
ns_param	.jpe		image/jpeg
ns_param	.jpe		image/pjpeg
ns_param	.jpeg		image/jpeg
ns_param	.jpg		image/jpeg
ns_param	.jps		image/x-jps
ns_param	.js		application/x-javascript
ns_param	.jut		image/jutvision
ns_param	.kar		audio/midi
ns_param	.ksh		application/x-ksh
ns_param	.latex		application/x-latex 
ns_param	.lha		application/octet-stream 
ns_param	.lsf		video/x-la-asf 
ns_param	.lsx		video/x-la-asf 
ns_param	.la		audio/nspaudio
ns_param	.lam		audio/x-liveaudio
ns_param	.latex		application/x-latex
ns_param	.lhx		application/octet-stream
ns_param	.list		text/plain
ns_param	.lma		audio/nspaudio
ns_param	.log		text/plain
ns_param	.lsp		application/x-lisp
ns_param	.lst		text/plain
ns_param	.lsx		text/x-la-asf
ns_param	.ltx		application/x-latex
ns_param	.lzh		application/x-lzh
ns_param	.lzx		application/lzx
ns_param	.m13		application/x-msmediaview 
ns_param	.m14		application/x-msmediaview 
ns_param	.mny		application/x-msmoney 
ns_param	.mpv2		video/mpeg 
ns_param	.mvb		application/x-msmediaview 
ns_param	.m		text/plain
ns_param	.m1v		video/mpeg
ns_param	.m2a		audio/mpeg
ns_param	.m2v		video/mpeg
ns_param	.m3u		audio/x-mpequrl
ns_param	.man		application/x-troff-man
ns_param	.map		application/x-navimap
ns_param	.mar		text/plain
ns_param	.mbd		application/mbedlet
ns_param	.mc$		application/x-magic-cap-package-1.0
ns_param	.mcd		application/mcad
ns_param	.mcf		text/mcf
ns_param	.mcp		application/netmc
ns_param        .mdb            application/msaccess
ns_param	.me		application/x-troff-me
ns_param	.mht		message/rfc822
ns_param	.mhtml		message/rfc822
ns_param	.mid		audio/midi
ns_param	.midi		audio/midi
ns_param	.mif		application/x-mif
ns_param	.mime		message/rfc822
ns_param	.mjf		audio/x-vnd.AudioExplosion.MjuiceMediaFile
ns_param	.mjpg		video/x-motion-jpeg
ns_param	.mm		application/base64
ns_param	.mme		application/base64
ns_param	.mod		audio/mod
ns_param	.moov		video/quicktime
ns_param	.mov		video/quicktime
ns_param	.movie		video/x-sgi-movie
ns_param	.mp2		audio/mpeg
ns_param	.mp3		video/mpeg
ns_param	.mpa		video/mpeg
ns_param	.mpc		application/x-project
ns_param	.mpe		video/mpeg
ns_param	.mpeg		video/mpeg
ns_param	.mpg		video/mpeg
ns_param	.mpga		audio/mpeg
ns_param	.mpp		application/vnd.ms-project
ns_param	.mpt		application/x-project
ns_param	.mpv		application/x-project
ns_param	.mpx		application/x-project
ns_param	.mrc		application/marc
ns_param	.ms		application/x-troff-ms
ns_param	.mv		video/x-sgi-movie
ns_param	.my		audio/make
ns_param	.mzz		application/x-vnd.AudioExplosion.mzz
ns_param	.nap		image/naplps
ns_param	.naplps		image/naplps
ns_param	.nc		application/x-netcdf
ns_param	.ncm		application/vnd.nokia.configuration-message
ns_param	.nif		image/x-niff
ns_param	.niff		image/x-niff
ns_param	.nix		application/x-mix-transfer
ns_param	.nsc		application/x-conference
ns_param	.nvd		application/x-navidoc
ns_param	.nws		message/rfc822 
ns_param	.o		application/octet-stream
ns_param	.oda		application/oda
ns_param	.omc		application/x-omc
ns_param	.omcd		application/x-omcdatamaker
ns_param	.omcr		application/x-omcregerator
ns_param	.p		text/x-pascal
ns_param	.p10		application/pkcs10
ns_param	.p12		application/pkcs-12
ns_param	.p7a		application/x-pkcs7-signature
ns_param	.p7c		application/pkcs7-mime
ns_param	.p7b		application/x-pkcs7-certificates 
ns_param	.p7c		application/x-pkcs7-mime 
ns_param	.p7m		application/x-pkcs7-mime 
ns_param	.p7r		application/x-pkcs7-certreqresp 
ns_param	.p7s		application/x-pkcs7-signature 
ns_param	.part		application/pro_eng
ns_param	.pas		text/pascal
ns_param	.pbm		image/x-portable-bitmap
ns_param	.pcl		application/x-pcl
ns_param	.pct		image/x-pict
ns_param	.pcx		image/x-pcx
ns_param	.pdb		chemical/x-pdb
ns_param	.pdf		application/pdf
ns_param	.pfunk		audio/make
ns_param	.pfx		application/x-pkcs12 
ns_param	.pgm		image/x-portable-graymap
ns_param	.pic		image/pict
ns_param	.pict		image/pict
ns_param	.pkg		application/x-newton-compatible-pkg
ns_param	.pko		application/vnd.ms-pki.pko
ns_param	.pl		text/plain
ns_param	.plx		application/x-PiXCLscript
ns_param	.pm		image/x-xpixmap
ns_param	.pma		application/x-perfmon 
ns_param	.pmc		application/x-perfmon 
ns_param	.pml		application/x-perfmon 
ns_param	.pmr		application/x-perfmon 
ns_param	.pmw		application/x-perfmon 
ns_param	.pm4		application/x-pagemaker
ns_param	.pm5		application/x-pagemaker
ns_param	.png		image/png
ns_param	.pnm		image/x-portable-anymap
ns_param	.pot		application/vnd.ms-powerpoint
ns_param	.pov		model/x-pov
ns_param	.ppa		application/vnd.ms-powerpoint
ns_param	.ppm		image/x-portable-pixmap
ns_param	.pps		application/vnd.ms-powerpoint
ns_param        .ppt            application/vnd.ms-powerpoint
ns_param	.ppz		application/vnd.mspowerpoint
ns_param	.pre		application/x-freelance
ns_param	.prt		application/pro_eng
ns_param	.ps		application/postscript
ns_param	.psd		application/octet-stream
ns_param	.pvu		paleovu/x-pv
ns_param	.pwz		application/vnd.ms-powerpoint
ns_param	.prf		application/pics-rules 
ns_param	.pub		application/x-mspublisher 
ns_param	.py		text/x-script.phyton
ns_param	.pyc		applicaiton/x-bytecode.python
ns_param	.qcp		audio/vnd.qcelp
ns_param	.qd3		x-world/x-3dmf
ns_param	.qd3d		x-world/x-3dmf
ns_param	.qif		image/x-quicktime
ns_param	.qt		video/quicktime
ns_param	.qtc		video/x-qtc
ns_param	.qti		image/x-quicktime
ns_param	.qtif		image/x-quicktime
ns_param	.ra		audio/x-pn-realaudio
ns_param	.ram		audio/x-pn-realaudio
ns_param	.ras		image/x-cmu-raster
ns_param	.rast		image/x-cmu-raster
ns_param	.rexx		text/x-script.rexx
ns_param	.rf		image/vnd.rn-realflash
ns_param	.rgb		image/x-rgb
ns_param	.rm		application/vnd.rn-realmedia
ns_param	.rm		audio/x-pn-realaudio
ns_param	.rmi		audio/mid
ns_param	.rmm		audio/x-pn-realaudio
ns_param	.rmp		audio/x-pn-realaudio
ns_param	.rmp		audio/x-pn-realaudio-plugin
ns_param	.rng		application/vnd.nokia.ringing-tone
ns_param	.rnx		application/vnd.rn-realplayer
ns_param	.roff		application/x-troff
ns_param	.rp		image/vnd.rn-realpix
ns_param	.rpm		audio/x-pn-realaudio-plugin
ns_param	.rt		text/richtext
ns_param        .rtf            application/msword
ns_param	.rtx		application/richtext
ns_param	.rv		video/vnd.rn-realvideo
ns_param	.scd		application/x-msschedule 
ns_param	.sct		text/scriptlet 
ns_param	.setpay		application/set-payment-initiation 
ns_param	.setreg		application/set-registration-initiation 
ns_param	.s		text/plain
ns_param	.s3m		audio/s3m
ns_param	.saveme		application/octet-stream
ns_param	.sbk		application/x-tbook
ns_param	.scm		video/x-scm
ns_param	.sdml		text/plain
ns_param	.sdp		application/sdp
ns_param	.sdr		application/sounder
ns_param	.sea		application/sea
ns_param	.set		application/set
ns_param	.sgm		text/sgml
ns_param	.sgml		text/sgml
ns_param	.sh		application/x-sh
ns_param	.shar		application/x-shar
ns_param	.shtml		text/html
ns_param	.sid		audio/x-psid
ns_param	.sit		application/x-stuffit
ns_param	.skd		application/x-koan
ns_param	.skm		application/x-koan
ns_param	.skp		application/x-koan
ns_param	.skt		application/x-koan
ns_param	.sl		application/x-seelogo
ns_param	.smi		application/smil
ns_param	.smil		application/smil
ns_param	.snd		audio/basic
ns_param	.sol		application/solids
ns_param	.spc		application/x-pkcs7-certificates
ns_param	.spl		application/futuresplash
ns_param	.spr		application/x-sprite
ns_param	.sprite		application/x-sprite
ns_param	.src		application/x-wais-source
ns_param	.ssi		text/x-server-parsed-html
ns_param	.ssm		application/streamingmedia
ns_param	.sst		application/vnd.ms-pki.certstore
ns_param	.step		application/step
ns_param	.stl		application/vnd.ms-pki.stl
ns_param	.stp		application/step
ns_param	.stm		text/html 
ns_param	.sv4cpio	application/x-sv4cpio
ns_param	.sv4crc		application/x-sv4crc
ns_param	.svf		image/vnd.dwg
ns_param	.svr		application/x-world
ns_param	.swf		application/x-shockwave-flash
ns_param	.trm		application/x-msterminal 
ns_param	.t		application/x-troff
ns_param	.talk		text/x-speech
ns_param	.tar		application/x-tar
ns_param	.tbk		application/toolbook
ns_param	.tcl		application/x-tcl
ns_param	.tcsh		text/x-script.tcsh
ns_param	.tex		application/x-tex
ns_param	.texi		application/x-texinfo
ns_param	.texinfo	application/x-texinfo
ns_param	.text		text/plain
ns_param	.tgz		application/x-compressed
ns_param	.tif		image/tiff
ns_param	.tiff		image/tiff
ns_param	.tr		application/x-troff
ns_param	.tsi		audio/tsp-audio
ns_param	.tsp		audio/tsplayer
ns_param	.tsv		text/tab-separated-values
ns_param	.turbot		image/florian
ns_param	.txt		text/plain
ns_param	.uil		text/x-uil
ns_param	.uni		text/uri-list
ns_param	.unis		text/uri-list
ns_param	.unv		application/i-deas
ns_param	.uri		text/uri-list
ns_param	.uris		text/uri-list
ns_param	.ustar		application/x-ustar
ns_param	.uu		text/x-uuencode
ns_param	.uue		text/x-uuencode
ns_param	.uls		text/iuls 
ns_param	.vcd		application/x-cdlink
ns_param	.vcs		text/x-vCalendar
ns_param	.vcf		text/x-vcard 
ns_param	.vda		application/vda
ns_param	.vdo		video/vdo
ns_param	.vew		application/groupwise
ns_param	.viv		video/vnd.vivo
ns_param	.vivo		video/vnd.vivo
ns_param	.vmd		application/vocaltec-media-desc
ns_param	.vmf		application/vocaltec-media-file
ns_param	.voc		audio/voc
ns_param	.vos		video/vosaic
ns_param	.vox		audio/voxware
ns_param	.vqe		audio/x-twinvq-plugin
ns_param	.vqf		audio/x-twinvq
ns_param	.vql		audio/x-twinvq-plugin
ns_param	.vrml		x-world/x-vrml 
ns_param	.vrt		x-world/x-vrt
ns_param        .vsd            application/vnd.visio
ns_param	.vst		application/x-visio
ns_param	.vsw		application/x-visio
ns_param	.wav		audio/x-wav 
ns_param	.wcm		application/vnd.ms-works 
ns_param	.wdb		application/vnd.ms-works 
ns_param	.wks		application/vnd.ms-works 
ns_param	.wmf		application/x-msmetafile 
ns_param	.w60		application/wordperfect6.0
ns_param	.w61		application/wordperfect6.1
ns_param	.w6w		application/msword
ns_param	.wb1		application/x-qpro
ns_param	.wbmp		image/vnd.wap.wbmp
ns_param	.web		application/vnd.xara
ns_param	.wiz		application/msword
ns_param	.wk1		application/x-123
ns_param        .wma            application/x-ms-wma
ns_param	.wml		text/vnd.wap.wml
ns_param	.wmlc		application/vnd.wap.wmlc
ns_param	.wmls		text/vnd.wap.wmlscript
ns_param	.wmlsc		application/vnd.wap.wmlscriptc
ns_param	.word		application/msword
ns_param	.wp		application/wordperfect
ns_param	.wp5		application/wordperfect
ns_param	.wp5		application/wordperfect6.0
ns_param	.wp6		application/wordperfect
ns_param	.wpd		application/wordperfect
ns_param	.wpd		application/x-wpwin
ns_param	.wq1		application/x-lotus
ns_param	.wps		application/vnd.ms-works 
ns_param	.wri		application/x-mswrite 
ns_param	.wrl		x-world/x-vrml 
ns_param	.wrz		x-world/x-vrml 
ns_param	.wsc		text/scriplet
ns_param	.wsrc		application/x-wais-source
ns_param	.wtk		application/x-wintalk
ns_param	.xaf		x-world/x-vrml 
ns_param	.x-png		image/png
ns_param	.xbm		image/x-xbitmap 
ns_param	.xdr		video/x-amt-demorun
ns_param	.xgz		xgl/drawing
ns_param	.xif		image/vnd.xiff
ns_param	.xl		application/excel
ns_param	.xla		application/vnd.ms-excel
ns_param	.xlb		application/vnd.ms-excel
ns_param	.xlc		application/vnd.ms-excel
ns_param	.xld		application/vnd.ms-excel
ns_param	.xlk		application/vnd.ms-excel
ns_param	.xll		application/vnd.ms-excel
ns_param	.xlm		application/vnd.ms-excel
ns_param        .xls            application/vnd.ms-excel
ns_param	.xlt		application/vnd.ms-excel
ns_param	.xlv		application/vnd.ms-excel
ns_param	.xlw		application/vnd.ms-excel
ns_param	.xm		audio/xm
ns_param	.xml		text/xml
ns_param	.xmz		xgl/movie
ns_param	.xpix		application/x-vnd.ls-xpix
ns_param	.xof		x-world/x-vrml 
ns_param	.xpm		image/x-xpixmap 
ns_param	.xsr		video/x-amt-showrun
ns_param	.xwd		image/x-xwindowdump 
ns_param	.xwd		image/x-xwindowdump
ns_param	.xyz		chemical/x-pdb
ns_param	.z		application/x-compress
ns_param	.zip		application/zip
ns_param	.zoo		application/octet-stream
ns_param	.zsh		text/x-script.zsh
