# Template C++ Application

# This template allows you to validate your C++ application.
# The workflow allows running tests and code linting on the default branch.


image: ubuntu:latest


pipelines:
  default:
    - parallel:
        - step:
            name: Setup
            script:
              - apt-get update
              - locale-gen en_US.UTF-8
              - update-locale LANG="en_US.UTF-8"
              - update-locale LC_ALL="en_US.UTF-8"
              - apt-get install -y git wget curl build-essential zlib1g-dev
              - git clone https://github.com/gustafn/install-ns.git
              - cd install-ns
              - bash install-ns.sh build
        - step:
            name: Test
            script:
              # apt update && apt -y install cppcheck && cppcheck .
              - make test
