#
# $Header$
#
# nsexample --
#
#      Example AOLserver module Makefile.
#

#
# Module name
#
MOD      =  nsexample.so

#
# Objects to build
#
OBJS     =  nsexample.o

#
# Header files
#
HDRS     =  

#
# Extra libraries
#
MODLIBS  =  

#
# Compiler flags
#
CFLAGS   =  


include  ../include/Makefile.module

