<%
set bucket [ns_queryget bucket]

#
# Capture logs generated by this connection thread.
#
ns_logctl hold

set bufsize [expr {4 * 1024}]
ns_adp_ctl bufsize $bufsize

nsv_set $bucket entered 1
nsv_set $bucket effective_bufsize [ns_adp_ctl bufsize]

while {![nsv_exists $bucket start]} {
    ns_sleep 1ms
}

nsv_set $bucket first_flush_started 1
ns_adp_append [string repeat x [expr {$bufsize + 1}]]
nsv_set $bucket first_flush_done 1

while {![nsv_exists $bucket client_closed]} {
    ns_sleep 1ms
}

ns_sleep 50ms
nsv_set $bucket failing_flush_started 1

#
# NsAdpFlush() logs the failure and sets ADP_ABORT before
# ns_adp_append returns TCL_ERROR. Catch the Tcl error so the test
# can retrieve the held log and publish its result.
#
set appendCode [catch {
    ns_adp_append [string repeat x [expr {4 * 1024 * 1024}]]
} appendResult]

set captured [ns_logctl get]
ns_logctl release

nsv_set $bucket append_code   $appendCode
nsv_set $bucket append_result $appendResult
nsv_set $bucket captured_log  $captured
nsv_set $bucket done          1

#
# This is set only if the disconnected-client write unexpectedly
# succeeded.
#
if {$appendCode == 0} {
    nsv_set $bucket continued 1
}
%>