# Emacs mode:  -*-Makefile-*-

# This is the Microsoft Windows specific file, for use with nmake.  Do
# NOT put Linux stuff here.

include Makefile.common
CLEAN = $(CLEAN) clean-cert
!message Debug: nsssl: HAVE_OPENSSL_EVP_H:  $(HAVE_OPENSSL_EVP_H)

_dhparams:
	openssl dhparam -C -2 -noout  512 >> dhparams-win.h
	openssl dhparam -C -2 -noout 1024 >> dhparams-win.h
