<header class="man-header">
  <div class="header-main">
    <div class="header-left">
      <a href="/"><strong>NaviServer</strong></a>
      <span class="tagline">Programmable Web Server</span>
    </div>
<!-- <div class="version-switcher">
      <a href="https://naviserver.sourceforge.io/5.0/toc.html" class="active" title="Switch to version 5.0">5.0</a>
      <a href="https://naviserver.sourceforge.io/4.99/toc.html" title="Switch to version 4.99">4.99</a>
    </div>-->
  </div>
<!--  <div class="man-info">
    <h1 class="man-title">@MAN_TITLE@</h1>
    <p class="man-details">@MAN_SECTION@ &ndash; @NS_VERSION@</p>
  </div>-->
</header>
